/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Tutorial
 * OpenAPI Tutorial by halhorn
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * リクエスト 職種登録
 * @export
 * @interface RequestJobCategory
 */
export interface RequestJobCategory {
    /**
     * 名称
     * @type {string}
     * @memberof RequestJobCategory
     */
    name: string;
    /**
     * 内容
     * @type {string}
     * @memberof RequestJobCategory
     */
    content: string;
    /**
     * 画像の内部識別子
     * @type {string}
     * @memberof RequestJobCategory
     */
    image: string;
    /**
     * 画像URL
     * @type {string}
     * @memberof RequestJobCategory
     */
    imageUrl?: string;
    /**
     * 並び順
     * @type {number}
     * @memberof RequestJobCategory
     */
    sortNo: number | null;
    /**
     * 更新日時
     * @type {Date}
     * @memberof RequestJobCategory
     */
    updatedAt?: Date;
}

export function RequestJobCategoryFromJSON(json: any): RequestJobCategory {
    return RequestJobCategoryFromJSONTyped(json, false);
}

export function RequestJobCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestJobCategory {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'content': json['content'],
        'image': json['image'],
        'imageUrl': !exists(json, 'imageUrl') ? undefined : json['imageUrl'],
        'sortNo': json['sortNo'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
    };
}

export function RequestJobCategoryToJSON(value?: RequestJobCategory | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'content': value.content,
        'image': value.image,
        'imageUrl': value.imageUrl,
        'sortNo': value.sortNo,
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString().substr(0,10)),
    };
}

