/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Tutorial
 * OpenAPI Tutorial by halhorn
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Job,
    JobFromJSON,
    JobFromJSONTyped,
    JobToJSON,
    User,
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './';

/**
 * レスポンス 仕事応募内容
 * @export
 * @interface ResponseJobEntry
 */
export interface ResponseJobEntry {
    /**
     * エントリーid
     * @type {number}
     * @memberof ResponseJobEntry
     */
    entryId?: number;
    /**
     * エントリー日時
     * @type {Date}
     * @memberof ResponseJobEntry
     */
    entryDate?: Date;
    /**
     * 
     * @type {User}
     * @memberof ResponseJobEntry
     */
    user?: User;
    /**
     * 
     * @type {Job}
     * @memberof ResponseJobEntry
     */
    job?: Job;
}

export function ResponseJobEntryFromJSON(json: any): ResponseJobEntry {
    return ResponseJobEntryFromJSONTyped(json, false);
}

export function ResponseJobEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseJobEntry {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'entryId': !exists(json, 'entryId') ? undefined : json['entryId'],
        'entryDate': !exists(json, 'entryDate') ? undefined : (new Date(json['entryDate'])),
        'user': !exists(json, 'user') ? undefined : UserFromJSON(json['user']),
        'job': !exists(json, 'job') ? undefined : JobFromJSON(json['job']),
    };
}

export function ResponseJobEntryToJSON(value?: ResponseJobEntry | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'entryId': value.entryId,
        'entryDate': value.entryDate === undefined ? undefined : (value.entryDate.toISOString().substr(0,10)),
        'user': UserToJSON(value.user),
        'job': JobToJSON(value.job),
    };
}

