version: '3'

services:
  php:
    container_name: php_lvs
    build: ./docker/php
    volumes:
    - ./project:/var/www/html
    - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    extra_hosts:
    - "host.docker.internal:host-gateway"
    networks:
      - lvs
    restart: always

  nginx:
    image: nginx:1.21.5
    container_name: nginx_lvs
    ports:
    - 80:80
    volumes:
    - ./project:/var/www/html
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php
    networks:
      - lvs
    restart: always

  db:
    image: mysql:5.7
    container_name: db_lvs
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 53306:3306
    networks:
      - lvs
    restart: always

  selenium:
    container_name: selenium_chrome_lvs
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
    networks:
      - lvs
    restart: always

networks:
  lvs: