/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Tutorial
 * OpenAPI Tutorial by halhorn
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * アクセストークン
 * @export
 * @interface AccessToken
 */
export interface AccessToken {
    /**
     * jwt
     * @type {string}
     * @memberof AccessToken
     */
    accessToken?: string;
    /**
     * トークンタイプ
     * @type {string}
     * @memberof AccessToken
     */
    tokenType?: string;
    /**
     * 有効期限(秒)
     * @type {number}
     * @memberof AccessToken
     */
    expiresIn?: number;
}

export function AccessTokenFromJSON(json: any): AccessToken {
    return AccessTokenFromJSONTyped(json, false);
}

export function AccessTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessToken {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessToken': !exists(json, 'accessToken') ? undefined : json['accessToken'],
        'tokenType': !exists(json, 'tokenType') ? undefined : json['tokenType'],
        'expiresIn': !exists(json, 'expiresIn') ? undefined : json['expiresIn'],
    };
}

export function AccessTokenToJSON(value?: AccessToken | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accessToken': value.accessToken,
        'tokenType': value.tokenType,
        'expiresIn': value.expiresIn,
    };
}

