/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Tutorial
 * OpenAPI Tutorial by halhorn
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * クエリパラメータ 職種一覧
 * @export
 * @interface QueryJobCategoryList
 */
export interface QueryJobCategoryList {
    /**
     * 名称
     * @type {string}
     * @memberof QueryJobCategoryList
     */
    name?: string;
    /**
     * 内容
     * @type {string}
     * @memberof QueryJobCategoryList
     */
    content?: string;
}

export function QueryJobCategoryListFromJSON(json: any): QueryJobCategoryList {
    return QueryJobCategoryListFromJSONTyped(json, false);
}

export function QueryJobCategoryListFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryJobCategoryList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'content': !exists(json, 'content') ? undefined : json['content'],
    };
}

export function QueryJobCategoryListToJSON(value?: QueryJobCategoryList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'content': value.content,
    };
}

