/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Tutorial
 * OpenAPI Tutorial by halhorn
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * クエリパラメータ 応募一覧
 * @export
 * @interface QueryEntryList
 */
export interface QueryEntryList {
    /**
     * 仕事id
     * @type {number}
     * @memberof QueryEntryList
     */
    jobId?: number;
    /**
     * 仕事カテゴリid
     * @type {number}
     * @memberof QueryEntryList
     */
    jobCategoryId?: number;
}

export function QueryEntryListFromJSON(json: any): QueryEntryList {
    return QueryEntryListFromJSONTyped(json, false);
}

export function QueryEntryListFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryEntryList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jobId': !exists(json, 'jobId') ? undefined : json['jobId'],
        'jobCategoryId': !exists(json, 'jobCategoryId') ? undefined : json['jobCategoryId'],
    };
}

export function QueryEntryListToJSON(value?: QueryEntryList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jobId': value.jobId,
        'jobCategoryId': value.jobCategoryId,
    };
}

