/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Tutorial
 * OpenAPI Tutorial by halhorn
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * リクエスト ログイン
 * @export
 * @interface RequestLogin
 */
export interface RequestLogin {
    /**
     * メールアドレス
     * @type {string}
     * @memberof RequestLogin
     */
    email: string;
    /**
     * パスワード
     * @type {string}
     * @memberof RequestLogin
     */
    password: string;
}

export function RequestLoginFromJSON(json: any): RequestLogin {
    return RequestLoginFromJSONTyped(json, false);
}

export function RequestLoginFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestLogin {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function RequestLoginToJSON(value?: RequestLogin | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'password': value.password,
    };
}

