version: "3"

services:
  php:
    container_name: b_lvs_php
    build: ./docker/php
    volumes:
      - ./project:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - b_lvs
    restart: always

  nginx:
    image: nginx:1.21.5
    container_name: b_lvs_nginx
    ports:
      - 80:80
    volumes:
      - ./project:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - b_lvs
    restart: always

  db:
    image: mysql:5.7
    container_name: b_lvs_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 53306:3306
    networks:
      - b_lvs
    restart: always
  test_db:
    image: mysql:5.7
    container_name: b_lvs_test_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/test_db/data:/var/lib/mysql
      - ./docker/test_db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/test_db/sql:/docker-entrypoint-initdb.d
    ports:
      - 53307:3306
    networks:
      - b_lvs
    restart: always

networks:
  b_lvs:
