version: '3'

services:
  php:
    container_name: php
    build: ./docker/php
    volumes:
    - ./project:/var/www/html
    restart: always

  nginx:
    image: nginx
    container_name: nginx
    ports:
    - 80:80
    volumes:
    - ./project:/var/www/html
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php
    restart: always
