openapi: 3.0.0
info:
  title: OpenAPI Tutorial
  description: OpenAPI Tutorial by halhorn
  version: 0.0.0
servers:
  - url: http://localhost:80/api
    description: 開発用
paths:
  /job_categories/{id}:
    get:
      tags:
        - "職種"
      summary: 1件取得
      description: 詳細内容
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: 職種
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseJobCategory"
    put:
      tags:
        - "職種"
      summary: 更新
      description: 詳細内容
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/requestJobCategory"
      responses:
        "200":
          description: 職種
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseJobCategory"
    delete:
      tags:
        - "職種"
      summary: 削除
      description: 詳細内容
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: 職種
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseJobCategory"
  /job_categories:
    get:
      tags:
        - "職種"
      summary: 一覧取得
      description: 詳細内容
      parameters:
        - in: query
          name: values
          schema:
            type: object
            $ref: "#/components/schemas/queryJobCategoryList"
          style: form
          explode: true
      responses:
        "200":
          description: 職種一覧
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/responseJobCategory"
    post:
      tags:
        - "職種"
      summary: 職種 追加
      description: 詳細内容
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/requestJobCategory"
      responses:
        "201":
          description: 職種
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseJobCategory"
  

  /jobs/{id}:
    get:
      tags:
        - "仕事"
      summary: 1件取得
      description: 詳細内容
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: 仕事
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseJob"
    put:
      tags:
        - "仕事"
      summary: 更新
      description: 詳細内容
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/requestJobCategory"
      responses:
        "200":
          description: 仕事
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseJob"
    delete:
      tags:
        - "仕事"
      summary: 削除
      description: 詳細内容
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: 仕事
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseJob"
  /jobs:
    get:
      tags:
        - "仕事"
      summary: 一覧取得
      description: 詳細内容
      parameters:
        - in: query
          name: values
          schema:
            type: object
            $ref: "#/components/schemas/queryJobList"
          style: form
          explode: true
      responses:
        "200":
          description: 仕事一覧
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/responseJob"
    post:
      tags:
        - "仕事"
      summary: 仕事 追加
      description: 詳細内容
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/requestJob"
      responses:
        "201":
          description: 仕事
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseJob"
  /entries:
    get:
      tags:
        - "応募"
      summary: 一覧取得
      description: 詳細内容
      parameters:
        - in: query
          name: values
          schema:
            type: object
            $ref: "#/components/schemas/queryEntryList"
          style: form
          explode: true
      responses:
        "200":
          description: 応募一覧
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/responseEntry"
    post:
      tags:
        - "応募"
      summary: 応募 追加
      description: 詳細内容
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/requestEntry"
      responses:
        "201":
          description: 応募
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseEntry"
  /users:
    get:
      tags:
        - "会員"
      summary: 一覧取得
      description: 詳細内容
      parameters:
        - in: query
          name: values
          schema:
            type: object
            $ref: "#/components/schemas/queryUserList"
          style: form
          explode: true
      responses:
        "200":
          description: 会員一覧
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/responseUser"
    post:
      tags:
        - "会員"
      summary: 会員 追加
      description: 詳細内容
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/requestUser"
      responses:
        "201":
          description: 会員
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseUser"
  /files:
    post:
      tags:
        - "ファイル"
      summary: ファイル 追加
      description: 詳細内容
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/requestFile"
      responses:
        "201":
          description: ファイルパス
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseFile"

components:
  schemas:
    queryJobCategoryList:
      description: クエリパラメータ 職種一覧
      type: object
      properties:
        name:
          type: string
          description: 名称
        content:
          type: string
          description: 内容
    queryJobList:
      description: クエリパラメータ 仕事一覧
      type: object
      properties:
        title:
          type: string
          description: タイトル
        content:
          type: string
          description: 内容
        attention:
          type: boolean
          description: 注目の求人
        jobCategoryId:
          type: integer
          description: 職種id
        price:
          type: integer
          description: 金額
        welfare:
          type: string
          description: 福利厚生
        holiday:
          type: string
          description: 休日
    queryEntryList:
      description: クエリパラメータ 応募一覧
      type: object
      properties:
        jobId:
          type: integer
          description: 仕事id
        jobCategoryId:
          type: integer
          description: 仕事カテゴリid
    queryUserList:
      description: クエリパラメータ 会員一覧
      type: object
      properties:
        name:
          type: string
          description: 氏名
        email:
          type: string
          description: メールアドレス
        selfPr:
          type: string
          description: 自己PR
        tel:
          type: string
          description: 電話番号
    requestJobCategory:
      description: リクエスト 職種登録
      type: object
      properties:
        name:
          type: string
          description: 名称
        content:
          type: string
          description: 内容
        image:
          type: string
          description: 画像URL
        sortNo:
          type: integer
          description: 並び順
        updatedAt:
          type: string
          format: date
          description: 更新日時
      required:
        - name
        - content
        - image
        - sortNo
        - updatedAt
    requestJob:
      description: リクエスト 仕事登録
      type: object
      properties:
        title:
          type: string
          description: タイトル
        content:
          type: string
          description: 内容
        attention:
          type: boolean
          description: 注目の求人
        jobCategoryId:
          type: integer
          description: 職種id
        price:
          type: integer
          description: 金額
        welfare:
          type: string
          description: 福利厚生
        holiday:
          type: string
          description: 休日
        image:
          type: string
          description: 画像URL
        sortNo:
          type: integer
          description: 並び順
        updatedAt:
          type: string
          format: date
          description: 更新日時
      required:
        - title
        - content
        - attention
        - jobCategoryId
        - price
        - image
        - sortNo
    requestEntry:
      description: リクエスト 応募登録
      type: object
      properties:
        jobId:
          type: integer
          description: 仕事id
        jobCategoryId:
          type: integer
          description: 仕事カテゴリid
      required:
        - jobId
        - jobCategoryId
    requestUser:
      description: リクエスト 会員登録
      type: object
      properties:
        name:
          type: string
          description: 氏名
        email:
          type: string
          description: メールアドレス
        password:
          type: string
          description: パスワード
        passwordConfirmation:
          type: string
          description: パスワード(確認)
        selfPr:
          type: string
          description: 自己PR
        tel:
          type: string
          description: 電話番号
      required:
        - name
        - email
        - password
        - passwordConfirmation
        - selfPr
        - tel
    requestFile:
      description: リクエスト ファイル
      type: object
      properties:
        file:
          type: string
          format: binary
          description: ファイル
      required:
        - file
    responseJobCategory:
      description: 職種
      type: object
      properties:
        id:
          type: integer
          description: id
        name:
          type: string
          description: 名称
        content:
          type: string
          description: 内容
        image:
          type: string
          description: 画像URL
        sortNo:
          type: integer
          description: 並び順
        createdAt:
          type: string
          format: date
          description: 作成日時
        updatedAt:
          type: string
          format: date
          description: 更新日時
    responseJob:
      description: 仕事
      type: object
      properties:
        id:
          type: integer
          description: id
        title:
          type: string
          description: タイトル
        content:
          type: string
          description: 内容
        attention:
          type: boolean
          description: 注目の求人
        jobCategoryId:
          type: integer
          description: 職種id
        price:
          type: integer
          description: 金額
        welfare:
          type: string
          description: 福利厚生
        holiday:
          type: string
          description: 休日
        image:
          type: string
          description: 画像URL
        sortNo:
          type: integer
          description: 並び順
        createdAt:
          type: string
          format: date
          description: 作成日時
        updatedAt:
          type: string
          format: date
          description: 更新日時
    responseEntry:
      description: 応募
      type: object
      properties:
        userId:
          type: integer
          description: 会員id
        jobId:
          type: integer
          description: 仕事id
    responseUser:
      description: 会員
      type: object
      properties:
        id:
          type: integer
          description: id
        name:
          type: string
          description: 氏名
        email:
          type: string
          description: メールアドレス
        password:
          type: string
          description: パスワード
        selfPr:
          type: string
          description: 自己PR
        tel:
          type: string
          description: 電話番号
        updatedAt:
          type: string
          format: date
          description: 更新日時
        createdAt:
          type: string
          format: date
          description: 作成日時
    responseFile:
      description: ファイルパス
      type: object
      properties:
        storagePath:
          type: string
          description: ストレージパス 
        url:
          type: string
          description: フルパス
    sex:
      description: |
        man: 男
        woman: 女
      enum: [1, 2]
      x-enum-varnames: [MAN, WOMAN]
