openapi: 3.0.0
info:
  title: OpenAPI Tutorial
  description: OpenAPI Tutorial by halhorn
  version: 0.0.0
servers:
  - url: http://localhost:80/api
    description: 開発用
paths:
  /job_categories/{id}:
    get:
      tags:
        - "職種"
      summary: 1件取得
      description: 詳細内容
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: 職種
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseJobCategory"
    put:
      tags:
        - "職種"
      summary: 更新
      description: 詳細内容
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/requestJobCategory"
      responses:
        "200":
          description: 職種
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseJobCategory"
    delete:
      tags:
        - "職種"
      summary: 削除
      description: 詳細内容
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: 職種
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseJobCategory"
  /job_categories:
    get:
      tags:
        - "職種"
      summary: 一覧取得
      description: 詳細内容
      parameters:
        - in: query
          name: values
          schema:
            type: object
            $ref: "#/components/schemas/queryJobCategoryList"
          style: form
          explode: true
      responses:
        "200":
          description: 職種一覧
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/responseJobCategory"
  /job_category:
    post:
      tags:
        - "職種"
      summary: 追加
      description: 詳細内容
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/requestJobCategory"
      responses:
        "200":
          description: 職種
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseJobCategory"
components:
  schemas:
    queryJobCategoryList:
      description: レスポンス 職種一覧
      type: object
      properties:
        name:
          type: string
          description: 名称
        content:
          type: string
          description: 内容
    responseJobCategory:
      description: 職種
      type: object
      properties:
        id:
          type: integer
          description: id
        name:
          type: string
          description: 名称
        content:
          type: string
          description: 内容
        image:
          type: string
          description: 画像URL
        sortNo:
          type: integer
          description: 並び順
        createdAt:
          type: string
          format: date
          description: 作成日時
        updatedAt:
          type: string
          format: date
          description: 更新日時
    requestJobCategory:
      description: 職種登録リクエスト
      type: object
      properties:
        name:
          type: string
          description: 名称
        content:
          type: string
          description: 内容
        image:
          type: string
          description: 画像URL
        sortNo:
          type: integer
          description: 並び順
        updatedAt:
          type: string
          format: date
          description: 更新日時
      required:
        - name
        - content
        - image
        - sortNo
        - updatedAt
    sex:
      description: |
        man: 男
        woman: 女
      enum: [1, 2]
      x-enum-varnames: [MAN, WOMAN]
