/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Tutorial
 * OpenAPI Tutorial by halhorn
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    AccessToken,
    AccessTokenFromJSON,
    AccessTokenToJSON,
    Admin,
    AdminFromJSON,
    AdminToJSON,
    RequestLogin,
    RequestLoginFromJSON,
    RequestLoginToJSON,
} from '../models';

export interface AuthAdminLoginPostRequest {
    requestLogin?: RequestLogin;
}

export interface AuthAdminRefreshPostRequest {
    authorization?: string;
    requestLogin?: RequestLogin;
}

/**
 * AuthAdminApi - interface
 * 
 * @export
 * @interface AuthAdminApiInterface
 */
export interface AuthAdminApiInterface {
    /**
     * 詳細内容
     * @summary ログイン
     * @param {RequestLogin} [requestLogin] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthAdminApiInterface
     */
    authAdminLoginPostRaw(requestParameters: AuthAdminLoginPostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<AccessToken>>;

    /**
     * 詳細内容
     * ログイン
     */
    authAdminLoginPost(requestParameters: AuthAdminLoginPostRequest, initOverrides?: RequestInit): Promise<AccessToken>;

    /**
     * 詳細内容
     * @summary ログアウト
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthAdminApiInterface
     */
    authAdminLogoutPostRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>>;

    /**
     * 詳細内容
     * ログアウト
     */
    authAdminLogoutPost(initOverrides?: RequestInit): Promise<void>;

    /**
     * 詳細内容
     * @summary 自身の詳細
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthAdminApiInterface
     */
    authAdminMeGetRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Admin>>;

    /**
     * 詳細内容
     * 自身の詳細
     */
    authAdminMeGet(initOverrides?: RequestInit): Promise<Admin>;

    /**
     * 詳細内容
     * @summary リフレッシュトークン認証
     * @param {string} [authorization] 
     * @param {RequestLogin} [requestLogin] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthAdminApiInterface
     */
    authAdminRefreshPostRaw(requestParameters: AuthAdminRefreshPostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<AccessToken>>;

    /**
     * 詳細内容
     * リフレッシュトークン認証
     */
    authAdminRefreshPost(requestParameters: AuthAdminRefreshPostRequest, initOverrides?: RequestInit): Promise<AccessToken>;

}

/**
 * 
 */
export class AuthAdminApi extends runtime.BaseAPI implements AuthAdminApiInterface {

    /**
     * 詳細内容
     * ログイン
     */
    async authAdminLoginPostRaw(requestParameters: AuthAdminLoginPostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<AccessToken>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/admin/login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RequestLoginToJSON(requestParameters.requestLogin),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccessTokenFromJSON(jsonValue));
    }

    /**
     * 詳細内容
     * ログイン
     */
    async authAdminLoginPost(requestParameters: AuthAdminLoginPostRequest, initOverrides?: RequestInit): Promise<AccessToken> {
        const response = await this.authAdminLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 詳細内容
     * ログアウト
     */
    async authAdminLogoutPostRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAdmin", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/auth/admin/logout`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * 詳細内容
     * ログアウト
     */
    async authAdminLogoutPost(initOverrides?: RequestInit): Promise<void> {
        await this.authAdminLogoutPostRaw(initOverrides);
    }

    /**
     * 詳細内容
     * 自身の詳細
     */
    async authAdminMeGetRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Admin>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAdmin", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/auth/admin/me`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminFromJSON(jsonValue));
    }

    /**
     * 詳細内容
     * 自身の詳細
     */
    async authAdminMeGet(initOverrides?: RequestInit): Promise<Admin> {
        const response = await this.authAdminMeGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * 詳細内容
     * リフレッシュトークン認証
     */
    async authAdminRefreshPostRaw(requestParameters: AuthAdminRefreshPostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<AccessToken>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters.authorization !== undefined && requestParameters.authorization !== null) {
            headerParameters['Authorization'] = String(requestParameters.authorization);
        }

        const response = await this.request({
            path: `/auth/admin/refresh`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RequestLoginToJSON(requestParameters.requestLogin),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccessTokenFromJSON(jsonValue));
    }

    /**
     * 詳細内容
     * リフレッシュトークン認証
     */
    async authAdminRefreshPost(requestParameters: AuthAdminRefreshPostRequest, initOverrides?: RequestInit): Promise<AccessToken> {
        const response = await this.authAdminRefreshPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
