name: Laravel

on:
  push:
    branches:
      - main

jobs:     
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: docker-setup
        working-directory: ./front/user
        run: |
          docker-compose up -d
          sleep 10
          
      - name: vue-setup
        working-directory: ./front/user
        run: |
          docker-compose exec -T vue sh ./setup.sh
          docker-compose exec -T vue npm run build
          
      - name: s3 test
        working-directory: ./front/user/project
        run: |
          ls
