name: Laravel

on:
  push:
    branches:
      - main

jobs:
  aws:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: ec2 test
        shell : sh
        run: |
          aws ssm start-session --target i-071fcff583cdee6b7
          aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --parameters "commands=['su ec2-user -c\'cd ~/ec2-user;git pull\'']" \
          --targets "Key=instanceids,Values=i-071fcff583cdee6b7" \
          --comment "git pull"
