name: Laravel

on:
  push:
    branches:
      - main

jobs:
  laravel-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: docker-setup
        working-directory: ./back
        run: |
          docker-compose up -d
          sleep 10
      - name: laravel-setup
        working-directory: ./back
        run: |
          docker-compose exec -T php sh ./setup.sh
      - name: laravel-test
        working-directory: ./back
        run: |
          docker-compose exec -T php sh php vendor/bin/phpstan analyse app --memory-limit=1G
          docker-compose exec -T php sh php artisan test
