name: Laravel

on:
  push:
    branches:
      - main

jobs:
  laravel-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: compose-run
        working-directory: ./functions
        run: |
          docker-compose up -d
      - name: laravel setup
        working-directory: ./functions
        run: |
          sleep 20
          setup.sh
