name: cicd

on:
  push:
    branches:
      - main

jobs:
  # デプロイ
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      # apiの更新
      - name: ec2のソースコードを更新します。
        env:
          AWS_EC2_INSTANCE: ${{ secrets.AWS_EC2_INSTANCE }}
        shell : sh
        run: |
          aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --parameters "commands=['sudo su ec2-user -c \'cd ~/laravel-vue;git pull\'']" \
          --targets "Key=instanceids,Values=${AWS_EC2_INSTANCE}" \
          --comment "git pull"
      # ユーザー画面の更新
      - name: docker-setup-front-user
        working-directory: ./front/user
        run: |
          docker-compose up -d
          sleep 10
          docker-compose exec -T vue sh ./setup.sh
          docker-compose exec -T vue npm run build
      - name: ユーザー側のバンドルファイルをs3へアップロードを行う。
        working-directory: ./front/user/project/dist
        run: |
          aws s3 cp ./ s3://portfolio-bucket-user --recursive
      # 管理画面の更新
      - name: docker-setup-admin-user
        working-directory: ./front/admin
        run: |
          docker-compose up -d
          sleep 10
          docker-compose exec -T vue sh ./setup.sh
          docker-compose exec -T vue npm run build
      - name: ユーザー側のバンドルファイルをs3へアップロードを行う。
        working-directory: ./front/admin/project/dist
        run: |
          aws s3 cp ./ s3://portfolio-bucket-admin --recursive

